package:
  name: torcharrow
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
  path: "{{ environ.get('SOURCE_ROOT_DIR') }}"

requirements:
  build:
    - cmake
    - python
  host:
    - python
    - setuptools
  run:
    - python
    - numpy
    - typing_inspect
    - pandas
    - typing
    - tabulate
    - pyarrow
    - arrow
    - cffi
    - glog==0.4.0
    - libsodium
    {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}

build:
  string: py{{py}}
  script_env:
    - BUILD_VERSION
    - CPU_TARGET

#GitHub Actions usually provide Mac without AVX2 support, for now just skip the test until Velox can be run without AVX2
#pytest --no-header -v torcharrow/test
test:
  imports:
    - torcharrow
  source_files:
    - torcharrow/test
  requires:
    - pytest

about:
  home: https://github.com/facebookresearch/torcharrow
  license: BSD
  license_file: LICENSE
  summary: "A torch.Tensor-like DataFrame library supporting multiple execution runtimes and Arrow as a common memory format."
  doc_url: https://github.com/facebookresearch/torcharrow/blob/main/tutorial/tutorial.ipynb
